// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animation_block': string;
  'animation_block_inner': string;
  'animation_char': string;
  'animation_icon_block': string;
  'animation_title': string;
  'animation_title_block': string;
  'content': string;
  'disabledWhenSmartphone': string;
  'inner': string;
  'loading_inner': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
