name: publish to npm repository after PR merged into master.
on:
  pull_request:
    branches: master
    types: closed

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Build components
        run: npm run build

      - name: Publish to npm repo
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
